#!/bin/bash

set -e

# JWT Signing Key
echo "Creating JWT Signing Key"
safe rsa 4096 "${VAULT_PREFIX}/jwt_signing_key"

# App ssh host key fingerprint
echo "Creating app_ssh host key fingerprint"
safe ssh 4096 "${VAULT_PREFIX}/app_ssh"

echo "Generating secrets"
safe gen ${VAULT_PREFIX}/creds/users/admin password -- \
   gen ${VAULT_PREFIX}/creds/cc bulk_api -- \
   gen ${VAULT_PREFIX}/creds/cc internal_api -- \
   gen ${VAULT_PREFIX}/creds/cc staging_upload -- \
   gen ${VAULT_PREFIX}/creds/cc db_encryption_key -- \
   gen ${VAULT_PREFIX}/creds/gorouter route_svcs_secret -- \
   gen ${VAULT_PREFIX}/creds/gorouter status_api_pass -- \
   gen ${VAULT_PREFIX}/creds/loggregator endpoint_secret -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets admin_client -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets cc_broker -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets cc_client -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets cc_routing -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets cc_user_lookup -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets doppler -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets gorouter -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets login -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets notifications -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets ssh_proxy -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets tcp_emitter -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets tcp_router -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets notifications_ui_client -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets autoscaler_client -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets opentsdb_firehose -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets identity -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets portal -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets usage_service -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets invitations -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets system_password -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets cc_service_dashboards -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets notifications_template -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets apps_metrics -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets apps_metrics_processing -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets pivotal_account -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets concourse_atc -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets push_notifications -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets push_api -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets greenplum_broker -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets greenplum_router_admin -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets greenplum_router -- \
   gen ${VAULT_PREFIX}/creds/nats password -- \
   gen ${VAULT_PREFIX}/creds/blobstore webdav_password -- \
   gen ${VAULT_PREFIX}/creds/blobstore secret -- \
   gen ${VAULT_PREFIX}/creds/diego encryption_key -- \
   gen ${VAULT_PREFIX}/creds/diego secret -- \
   gen ${VAULT_PREFIX}/creds/db uaaadmin -- \
   gen ${VAULT_PREFIX}/creds/db ccadmin -- \
   gen ${VAULT_PREFIX}/creds/db diegoadmin -- \
   gen ${VAULT_PREFIX}/uaadb password -- \
   gen ${VAULT_PREFIX}/ccdb password -- \
   gen ${VAULT_PREFIX}/diegodb password -- \
   >/dev/null
